apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dev-externalsecret
  namespace: dev
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: app-secrets                   # external secret will create or update this kubernetes secrets called app-secrets  late this is used inside deployment
    creationPolicy: Owner

  dataFrom:
    - extract:                          # it will extract all key  inside secrets
        key: dev-secrets        #this is name of secret inside AWS secret manager