apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: med-erp

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: app-secrets
    creationPolicy: Owner

  data:
    - secretKey: MONGODB_URI_USER
      remoteRef:
        key: application-secrets
        property: MONGODB_URI_USER

    - secretKey: MONGODB_URI_PRODUCT
      remoteRef:
        key: application-secrets
        property: MONGODB_URI_PRODUCT

    - secretKey: MONGODB_URI_ORDER
      remoteRef:
        key: application-secrets
        property: MONGODB_URI_ORDER

    - secretKey: JWT_SECRET
      remoteRef:
        key: application-secrets
        property: JWT_SECRET