apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace/namespace.yaml
  - configmaps/app-config.yaml
  - external-secrets/app-external-secret.yaml

  - deployments/user-service-deployment.yaml
  - deployments/product-service-deployment.yaml
  - deployments/order-service-deployment.yaml

  - services/services.yaml
  - hpa/hpa.yaml
  - ingress/ingress.yaml