namespace: dev
########################################################################
userService:
  replicas: 2

  image:
    repository: 655887417250.dkr.ecr.ap-southeast-1.amazonaws.com/dev-user-service
    tag: 33
  
  imagePullPolicy: Always
  
  terminationGracePeriodSeconds: 60
  containerPort: 8081
  
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

####################################################################
productService:
  replicas: 2

  image:
    repository: 655887417250.dkr.ecr.ap-southeast-1.amazonaws.com/dev-product-service
    tag: 31
  
  imagePullPolicy: Always
  
  terminationGracePeriodSeconds: 60
  containerPort: 8082
  
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
########################################################################################
orderService:
  replicas: 2

  image:
    repository: 655887417250.dkr.ecr.ap-southeast-1.amazonaws.com/dev-order-service
    tag: 32
  
  imagePullPolicy: Always
  
  terminationGracePeriodSeconds: 60
  containerPort: 8083
  
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
##################################################################################

serviceUser:
  targetPort: 8081
  port: 8081

serviceProduct:
  targetPort: 8082
  port: 8082

serviceOrder:
  targetPort: 8083
  port: 8083
#######################################################################################
hpaUser:
  minReplicas: 2
  maxReplicas: 6
  cpuAverageUtilization: 70
  memAverageUtilization: 80

hpaProduct:
  minReplicas: 2
  maxReplicas: 8
  cpuAverageUtilization: 70
  memAverageUtilization: 80

hpaOrder:
  minReplicas: 2
  maxReplicas: 6
  cpuAverageUtilization: 70
  memAverageUtilization: 80

########################################################################################
externalSecrets:
  name: dev-externalsecret
  extract:
    key: dev-secrets
###################################################################################
ingress:
  loadBalancerName: dev-med-erp-alb
  acmCertificate: arn:aws:acm:ap-southeast-1:655887417250:certificate/0adceb30-d07b-407a-ac13-e252648f0c6b
  securityGroup: sg-0b323fb613b8d1efd
  tagEnvironment: dev
  host: dev.api.cloudking.fun